# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fc9ab9343db79502e27c3e9be7d892eadd400058e870da9632887e359b3022700914fd92854666a32b407cabae4259218a18e0737a069e411446cd987efd8b2

test:
  secret_key_base: 6bcee236e7aa7c6b869a707919ac7c243a39a88fd49d6d4579f22e26bf1e90ced0848724c0b3174a0964da7df5ccd57afe08aa9ae117b454244de0efaddcdb18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
